AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
Style/Documentation:
  Enabled: false
Style/RegexpLiteral:
  AllowInnerSlashes: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented_relative_to_receiver
Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'
Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
Metrics/BlockLength:
  ExcludedMethods: [
    'describe',
    'context',
    'shared_examples',
    'namespace'
  ]
  Exclude:
    - 'config/environments/*'
Style/MixinUsage:
  Exclude:
    - 'db/seeds.rb'
    - 'bin/*'
