require: rubocop-rspec
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'config/environments/*'
  ExcludedMethods:
    - 'describe'
